package map;
// Generated 28-feb-2022 22:23:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private int idCategoria;
     private String nombreCategoria;
     private Double salarioBaseCategoria;
     private Double complementoCategoria;
     private Set trabajadorbbdds = new HashSet(0);

    public Categorias() {
    }

	
    public Categorias(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categorias(int idCategoria, String nombreCategoria, Double salarioBaseCategoria, Double complementoCategoria, Set trabajadorbbdds) {
       this.idCategoria = idCategoria;
       this.nombreCategoria = nombreCategoria;
       this.salarioBaseCategoria = salarioBaseCategoria;
       this.complementoCategoria = complementoCategoria;
       this.trabajadorbbdds = trabajadorbbdds;
    }
   
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public Double getSalarioBaseCategoria() {
        return this.salarioBaseCategoria;
    }
    
    public void setSalarioBaseCategoria(Double salarioBaseCategoria) {
        this.salarioBaseCategoria = salarioBaseCategoria;
    }
    public Double getComplementoCategoria() {
        return this.complementoCategoria;
    }
    
    public void setComplementoCategoria(Double complementoCategoria) {
        this.complementoCategoria = complementoCategoria;
    }
    public Set getTrabajadorbbdds() {
        return this.trabajadorbbdds;
    }
    
    public void setTrabajadorbbdds(Set trabajadorbbdds) {
        this.trabajadorbbdds = trabajadorbbdds;
    }




}


